version: "3"
services:
    cassandra:
        image: "cassandra"
        container_name: "botweet-cassandra"
        ports:
            - "7000:7000"
            - "7001:7001"
            - "7199:7199"
            - "9042:9042"
            - "9160:9160"