version: "3"
services:
    cassandra:
        image: "cassandra:latest"
        container_name: "cassandra"
        network_mode: "host"
    botweet-api:
        image: "botweet-api"
        container_name: "botweet-api"
        network_mode: "host"
        depends_on:
            - cassandra
        volumes:
            - "./tweets-api:/usr/dev/tweets-api"
        restart: on-failure:10 # Will try to restart 10 times