version: "3"
services:
    botweet-cassandra:
        image: "cassandra:latest"
        container_name: "botweet-cassandra"
        network_mode: "host"
        # healthcheck extracted from https://stackoverflow.com/questions/40443617/init-script-for-cassandra-with-docker-compose
        healthcheck:
            test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
            interval: 15s
            timeout: 10s
            retries: 10
    # service extracted from https://stackoverflow.com/questions/40443617/init-script-for-cassandra-with-docker-compose
    botweet-cassandra-load-keyspace:
        container_name: botweet-cassandra-load-keyspace
        image: cassandra:latest
        network_mode: "host"
        depends_on:
            botweet-cassandra:
                condition: service_healthy
        volumes:
            - ./database/create-database.cql:/usr/dev/database/create-database.cql
        command: /bin/bash -c "echo loading cassandra keyspace && cqlsh -f /usr/dev/database/create-database.cql"
    botweet-api:
        image: "botweet-api"
        container_name: "botweet-api"
        network_mode: "host"
        depends_on:
            - botweet-cassandra-load-keyspace
        volumes:
            - "./tweets-api:/usr/dev/tweets-api"
        restart: on-failure:10 # Will try to restart 10 times
    botweet-hashtag-loader-node:
        image: "botweet-hashtag-loader-node"
        container_name: "botweet-hashtag-loader-node"
        network_mode: "host"
        depends_on:
            - botweet-cassandra-load-keyspace
        volumes:
            - "./hashtag-loader-node:/usr/dev/hashtag-loader-node"
        restart: on-failure:10