version: "3"
services:
    cassandra:
        image: "cassandra:latest"
        container_name: "cassandra"
        network_mode: "host"
    botweet-api:
        image: "botweet-api"
        container_name: "botweet-api"
        network_mode: "host"
        volumes:
            - "./tweets-api:/usr/dev/tweets-api"